### ISSUE TITLE
Adding tag with whitespace fails

### ISSUE THREAD

**Issue by robgha01** [Geta/Tags#13]
When we add a tag  with whitespace all tags stops wrorking untill we remove the added tag and run the tag cleanup job. we tested "word wordb 2014" without quotes

Installed with the latest nuget package.

![image](https://cloud.githubusercontent.com/assets/362726/4614778/9e3bc72e-52e3-11e4-8a1c-8f8b008e642d.png)

**Comment by frederikvig** [comment]
Tested and verified that it works fine with "word wordb 2014" without quotes in the latest version.
