### ISSUE TITLE
Autocomplete(Save) not working for example MediaData. Not full support for tags within all types av IContent

### ISSUE THREAD

**Issue by icecold87** [Geta/Tags#17]
Hi,

Can you please provide support for IContent instead of just PageData? Currently the autocomplete are not working within types like blockdata and mediadata. 
I believe there is more developers out there including yourselves that wanna be able to have full support and tags for different types of data with this in EPiServer. 
Below is just a very quick fix for it to work on these types (PageData, BlockData and MediaData), for saving new tags in the DDS and beeing able to fetch them in autocomplete. Thanks in advance and great job building this Tag engine!

Changes in TagsScheduledJob.cs

using System;
using System.Collections.Generic;
using System.Linq;
using EPiServer;
using EPiServer.BaseLibrary.Scheduling;
using EPiServer.Core;
using EPiServer.DataAbstraction;
using EPiServer.PlugIn;
using EPiServer.ServiceLocation;
using Geta.Tags.Implementations;
using Geta.Tags.Interfaces;
using Geta.Tags.Models;
using Geta.Tags.Helpers;

namespace Geta.Tags
{
    [ScheduledPlugIn(DisplayName = "Geta Tags maintenance", DefaultEnabled = true)]
    public class TagsScheduledJob : JobBase
    {
        private bool _stop;

        private readonly ITagService _tagService;
        private readonly IContentTypeRepository _pageTypeRepository;

        public TagsScheduledJob() : this(new TagService())
        {
            IsStoppable = true;
        }

        public TagsScheduledJob(ITagService tagService)
        {
            _tagService = tagService;
            _pageTypeRepository = ServiceLocator.Current.GetInstance<IContentTypeRepository>();
        }

        public override string Execute()
        {
            var tags = _tagService.GetAllTags().ToList();
            var pageGuids = GetTaggedPageGuids(tags);

            foreach (var pageGuid in pageGuids)
            {
                if (_stop)
                {
                    return "Geta Tags maintenance was stopped";
                }

                IContent page = null;

                try
                {
                    var contentReference = TagsHelper.GetPageReference(pageGuid);

                    if (!ContentReference.IsNullOrEmpty(contentReference))
                    {
                        page = DataFactory.Instance.GetPage(contentReference);
                    }
                }
                catch (PageNotFoundException) {}

                if (page == null || page.IsDeleted)
                {
                    RemoveFromAllTags(pageGuid, tags);
                    continue;
                }

                CheckPageProperties(page, tags);
            }

            return "Geta Tags maintenance completed successfully";
        }

        private void CheckPageProperties(IContent page, IList<Tag> tags)
        {
            var pageType = _pageTypeRepository.Load(page.ContentTypeID);

            foreach (var propertyDefinition in pageType.PropertyDefinitions)
            {
                if (!TagsHelper.IsTagProperty(propertyDefinition))
                {
                    continue;
                }

                string tagNames = null;

                if (page is PageData)
                {
                    var pd = page as PageData;
                    tagNames = pd[propertyDefinition.Name] as string;
                }

                if (page is BlockData)
                {
                    var bd = page as BlockData;
                    tagNames = bd[propertyDefinition.Name] as string;
                }

                if (page is MediaData)
                {
                    var md = page as MediaData;
                    tagNames = md[propertyDefinition.Name] as string;
                }

                IList<Tag> allTags = tags;

                if (tagNames == null)
                {
                    RemoveFromAllTags(page.ContentGuid, allTags);
                    continue;
                }

                var addedTags = ParseTags(tagNames);

                // make sure the tags it has added has the pagereference
                ValidateTags(allTags, page.ContentGuid, addedTags);

                // make sure there's no pagereference to this pagereference in the rest of the tags
                RemoveFromAllTags(page.ContentGuid, allTags);
            }
        }

        private static IEnumerable<Guid> GetTaggedPageGuids(IEnumerable<Tag> tags)
        {
            return tags.Where(x => x != null && x.PermanentLinks != null)
                .SelectMany(x => x.PermanentLinks)
                .ToList();
        }

        private IEnumerable<Tag> ParseTags(string tagNames)
        {
            return tagNames.Split(',')
                .Select(_tagService.GetTagByName)
                .Where(tag => tag != null)
                .ToList();
        }

        private void ValidateTags(ICollection<Tag> allTags, Guid pageGuid, IEnumerable<Tag> addedTags)
        {
            foreach (var addedTag in addedTags)
            {
                allTags.Remove(addedTag);

                if (addedTag.PermanentLinks.Contains(pageGuid)) continue;

                addedTag.PermanentLinks.Add(pageGuid);

                _tagService.Save(addedTag);
            }
        }

        private void RemoveFromAllTags(Guid guid, IEnumerable<Tag> tags)
        {
            foreach (var tag in tags)
            {
                if (tag.PermanentLinks == null || !tag.PermanentLinks.Contains(guid)) continue;

                tag.PermanentLinks.Remove(guid);

                _tagService.Save(tag);
            }
        }

        public override void Stop()
        {
            _stop = true;
        }
    }
}

Changes in TagsModule.cs

using System;
using System.Collections.Generic;
using System.Linq;
using EPiServer;
using EPiServer.Core;
using EPiServer.DataAbstraction;
using EPiServer.Framework;
using EPiServer.Framework.Initialization;
using EPiServer.ServiceLocation;
using Geta.Tags.Helpers;
using Geta.Tags.Implementations;
using Geta.Tags.Interfaces;

namespace Geta.Tags
{
    [ModuleDependency(typeof (ServiceContainerInitialization))]
    public class TagsModule : IInitializableModule
    {
        private ITagService _tagService;
        private IContentTypeRepository _pageTypeRepository;

        private void OnPublishedPage(object sender, ContentEventArgs e)
        {
            var page = e.Content;
            var tags = GetPageTags(page);
            _tagService.Save(page.ContentGuid, tags);
        }

        private IEnumerable<string> GetPageTags(IContent page)
        {
            var pageType = _pageTypeRepository.Load(page.ContentTypeID);

            return pageType.PropertyDefinitions
                .Where(TagsHelper.IsTagProperty)
                .SelectMany(x => GetPropertyTags(page, x));
        }

        private static IEnumerable<string> GetPropertyTags(IContent page, PropertyDefinition propertyDefinition)
        {
            string tagNames = null;

            if (page is PageData)
            {
               var pd = page as PageData;
               tagNames = pd[propertyDefinition.Name] as string;
            } 

            if(page is BlockData)
            {
                var bd = page as BlockData;
                tagNames = bd[propertyDefinition.Name] as string;
            }

            if(page is MediaData)
            {
                var md = page as MediaData;
                tagNames = md[propertyDefinition.Name] as string;
            }

            return tagNames == null
                ? Enumerable.Empty<string>()
                : tagNames.Split(new[] {','}, StringSplitOptions.RemoveEmptyEntries);
        }

        public void Initialize(InitializationEngine context)
        {
            _tagService = new TagService();
            _pageTypeRepository = ServiceLocator.Current.GetInstance<IContentTypeRepository>();

            DataFactory.Instance.PublishedContent += OnPublishedPage;
        }

        public void Uninitialize(InitializationEngine context)
        {
            DataFactory.Instance.PublishedPage -= OnPublishedPage;
        }

        public void Preload(string[] parameters)
        {
        }
    }
}

**Comment by frederikvig** [comment]
Version 2 and above of Geta.Tags now supports other types of content like MediaData and BlockData.
