### ISSUE TITLE
Add tag, remove tag, but still the page gets found thru the TagEngine

### ISSUE THREAD

**Issue by wiske80** [Geta/Tags#20]
Hi guys,

i'm experiencing a strange thing. I hope you can replicate this.

- Create a new page. (with tag property)
- add 1 tag to the page, publish (e.g "tagname" )
- tagEngine.GetContentReferencesByTags("tagname", homepage.ContentLink) => fetched all references including my page. 
- open the created page and remove the added tag. Publish the page. ( so no tags anymore)
- run the tagEngine.GetContentReferencesByTags("tagname", homepage.ContentLink) again. Here is still see the page it fetched even though it doesnt has the tag anymore. 

I have this problem with more pages.. All pages that once had the tag and now are removed, are always fetched when asking for a tag it once had... 

Hope you can replicate this also, but more importantly fix it soon, as a client found this problem... Using the latest Geta Tags with latest EPiServer 8.8.*

P.S i could reproduce this on a clean MVC Alloy site as well...

**Comment by frederikvig** [comment]
I can confirm this behavior. We have a scheduled job called "Geta Tags maintenance" that can be run to clean up removed tags. I do see that it would be useful that it got updated when published - I'll add this as an enhancement for the next release. For now you can setup the scheduled job to run as often as you require.

Hope this helps and thanks for reporting this.

Frederik

**Comment by wiske80** [comment]
Thanks Frederik.. I didn't knew about the scheduled job.. I'm running it now every hour. Just to be sure. 
The client has been informed that it could take up to at least an hour before pages are removed from the overview. For now this is a workable solution. But hope to get a update soon.

**Comment by frederikvig** [comment]
Fixed in version 2.0.3 and later.

**Comment by wiske80** [comment]
awesome! When can we expect the 2.0.3 to be pushed to the EPi nuget feed?

**Comment by frederikvig** [comment]
Uploaded, but waiting for approval. Hopefully in a day or two.

**Comment by frederikvig** [comment]
And it's live :)

**Comment by wiske80** [comment]
awesome! thanks mate!
