### ISSUE TITLE
Seperate suggestions per language/site

### ISSUE THREAD

**Issue by kizzaz** [Geta/Tags#21]
We have a multi-site/lingual there all languages gets the same suggestions for tags. So for example Norwegian and Danish are really close and easy to pick the wrong tag. Either have a seperate example "feed" for each site or for each country.

**Comment by frederikvig** [comment]
Possible with GroupKey now. Use the TagsGroupKeyAttribute and/or the CultureSpecificAttribute:

```
[TagsGroupKey("mysite")]
public virtual string Tags { get; set; }

[CultureSpecific]
public virtual string Tags { get; set; }
```

**Comment by Ayoubezzddine** [comment]
if we used [TagsGroupKey("mysite")], how to get AllTags by (TagsGroupKey)?
