### ISSUE TITLE
Tags not saving/getting deleted

### ISSUE THREAD

**Issue by Taseldo** [Geta/Tags#22]
Hello!

We got a really weird bug showing up in geta-tags.
Some tags/words seems to be causing the modul to delete tags when you publish/save.
There is no special characters in the words that causes the bug to appear.

There is no errors showing up in log4net.
Sometimes I get error-message in chrome, however sometimes there are no errors there either oddly enough.

TypeError: Cannot read property 'tagName' of undefined
    at _68.placeAt (widgets.js:2)
    at _191b.addChild (widgets.js:2)
    at Object.addWidgetToRootFunction (widgets.js:2)
    at null.<anonymous> (widgets.js:2)
    at dojo.js:15
    at _2f2 (dojo.js:15)
    at Promise.then._2ff.then (dojo.js:15)
    at when (dojo.js:15)
    at _5f1._createInternal (widgets.js:2)
    at null.<anonymous> (widgets.js:2)(anonymous function) @ widgets.js:2
2widgets.js:2 

TypeError: Cannot read property 'appendChild' of null
    at Object.place (dojo.js:15)
    at _13d.addChild (widgets.js:2)
    at _19e (dojo.js:15)
    at _6b7.addChild (widgets.js:2)
    at _19e (dojo.js:15)
    at _1256.addChild (widgets.js:2)
    at _19e (dojo.js:15)
    at _191b.addChild (widgets.js:2)
    at Object.addWidgetToRootFunction (widgets.js:2)
    at null.<anonymous> (widgets.js:2)(anonymous function) @ widgets.js:2
widgets.js:2 WidgetFactory: Could not resolve one or more widgets(anonymous function) @ widgets.js:2
widgets.js:2 

TypeError: Cannot read property 'tagName' of undefined
    at _68.placeAt (widgets.js:2)
    at _191b.addChild (widgets.js:2)
    at Object.addWidgetToRootFunction (widgets.js:2)
    at null.<anonymous> (widgets.js:2)
    at dojo.js:15
    at _2f2 (dojo.js:15)
    at Promise.then._2ff.then (dojo.js:15)
    at when (dojo.js:15)
    at _5f1._createInternal (widgets.js:2)
    at null.<anonymous> (widgets.js:2)(anonymous function) @ widgets.js:2

Any help or tips on how to proceed would be greatly appreciated!

**Comment by frederikvig** [comment]
Could you try again with version 2.1.2? Thanks

**Comment by Taseldo** [comment]
Ok I will try that, thank you.
I just got to solve a problem with another widget not supporting CMS Core v9 first, because its preventing me from updating geta tags.

**Comment by Taseldo** [comment]
Unfortunately an update did not solve the issue.
Do you have any other ideas regarding what to do?

**Comment by garkavy** [comment]
Could you please clarify what "words, tags" cause the issue?

**Comment by frederikvig** [comment]
@Taseldo could you try again with the latest version please

**Comment by ezsearch** [comment]
Hi Frederikvig - I have the same problem. I just found out that save/update isn't working. I tried doing the following

        [CultureSpecific]
        [Display(
            Name = "Tags",
            Description = "Click to enter tags for this page",
            GroupName = SystemTabNames.Content,
            Order = 80)]
        [UIHint("Tags")]
        public virtual string Tags { get; set; }

**Comment by frederikvig** [comment]
@ezsearch does the auto save trigger after you change/update the tags textbox? Are you on the latest version of Tags?

**Comment by ezsearch** [comment]
I am on latest version of Tags, got that yesterday. No the auto save did not trigger.

**Comment by ezsearch** [comment]
Here is my package config in my project: 
  <package id="Antlr" version="3.4.1.9004" targetFramework="net45" />
  <package id="Castle.Core" version="3.3.3" targetFramework="net45" />
  <package id="Castle.Windsor" version="3.3.0" targetFramework="net45" />
  <package id="EntityFramework" version="6.0.0" targetFramework="net45" />
  <package id="EPiServer.CMS" version="9.4.0" targetFramework="net45" />
  <package id="EPiServer.CMS.Core" version="9.4.0" targetFramework="net45" />
  <package id="EPiServer.CMS.UI" version="9.3.3" targetFramework="net45" />
  <package id="EPiServer.CMS.UI.Core" version="9.3.3" targetFramework="net45" />
  <package id="EPiServer.Framework" version="9.4.0" targetFramework="net45" />
  <package id="EPiServer.Logging.Log4Net" version="1.1.0" targetFramework="net45" />
  <package id="EPiServer.Packaging" version="3.2.3" targetFramework="net45" />
  <package id="EPiServer.Packaging.UI" version="3.2.3" targetFramework="net45" />
  <package id="EPiServer.Search" version="8.0.0" targetFramework="net45" />
  <package id="Geta.Tags" version="2.1.4" targetFramework="net45" />
  <package id="log4net" version="1.2.10" targetFramework="net45" />
  <package id="Lucene.Net" version="3.0.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Providers.Core" version="2.0.0" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net45" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="6.0.8" targetFramework="net45" />
  <package id="NuGet.Core" version="2.5.0" targetFramework="net45" />
  <package id="PagedList" version="1.17.0.0" targetFramework="net45" />
  <package id="PagedList.Mvc" version="4.5.0.0" targetFramework="net45" />
  <package id="SharpZipLib" version="0.86.0" targetFramework="net45" />
  <package id="structuremap.web-signed" version="3.1.6.186" targetFramework="net45" />
  <package id="structuremap-signed" version="3.1.6.186" targetFramework="net45" />
  <package id="WebGrease" version="1.5.2" targetFramework="net45" />

**Comment by ezsearch** [comment]
@frederikvig - not sure why. I some how think that this issue is related to #16.

**Comment by Taseldo** [comment]
@garkavy I think the problem might be with already used words, possibly in connection to the auto-complete (see below)

@frederikvig I tried to upgrade and it did not fix this issue. 

I think @ezsearch is on to something.
It seems that this error occurs at the same that episerver is unable to detect the change.
It also seems to me that when episerver is unable to detect the change, is when I use the auto complete on tags that the system knows from before.

**Comment by Ayoubezzddine** [comment]
When you write the word, do not press enter, just click on the suggested tag.
That work for me.

**Comment by marisks** [comment]
Fixed by: #34
