### ISSUE TITLE
Possiblity to only allow editors to choose from existing tags. 

### ISSUE THREAD

**Issue by PNergard** [Geta/Tags#23]
It would be great if it was possible to only let editors choose from existing tags.

To manage tags a simple admin plugin page would be nice.

It would also be great to have two tag stores. One with tags where editors can add tags and one that only admins can add tags to from a admin plugin or something like that.

Maximum flexibility :)

**Comment by frederikvig** [comment]
Added the option to have a read-only Tag property and together with GroupKey you can have a different source for it as well. I agree on Admin plugin page, we have an open issue for it: #19 - so will close this now.
