### ISSUE TITLE
Tags not working for EPi9

### ISSUE THREAD

**Issue by kizzaz** [Geta/Tags#27]
When using Tags in Epi 9.2 you get error on publishing on blocks/media
Error: Value cannot be null, Parameter name: element", seems like it is a dependency on a old version of Structuremap that makes the problem after debugging around.

  <package id="structuremap" version="2.6.4.1" targetFramework="net45" />
Should be version Version=3.1.6.186, this is for Geta.Tags 2.1.0

**Comment by frederikvig** [comment]
Thanks - dependencies were messed up. Fixed in version 2.1.1.

**Comment by kizzaz** [comment]
Still have  the problem with the blocks not saving, getting the error "Error: Value cannot be null, Parameter name: element" if we try to publish changes/new blocks or media, works fine after removing Geta.Tags from the project

**Comment by garkavy** [comment]
I confirm the issue, the error occurs even without having tags anywhere, just by adding it to the project.

**Comment by frederikvig** [comment]
Fixed in version 2.1.2
