### ISSUE TITLE
tags not working when upgrading from EPi 8.xx to 9.xx and also geta.tags 

### ISSUE THREAD

**Issue by wiske80** [Geta/Tags#29]
Hey Guys,

we have a client working with geta.tags on epi 8.xx and on production.

We are doing a new release, and on our test env. we upgraded to Epi 9.xx and consequently updated Geta Tags to the latest version as well.

The problem is that existing tags in properties are not visible in the CMS. however, the front-end still shows the tags. So they are there. Also i cannot add new tags. I dont get autocomplete function when typing. I dont get any console errors either.. 

I can see that when typing in the property, the following api is getting called <domain>/getatags?groupKey=en-US&term=agenda
However whatever i type, the array is always empty.

This is a serious problem now, because we cannot put this non-working version live again and we are working against a deadline. So any input would be helpful...

thanks alot.

**Comment by frederikvig** [comment]
Does the property in your content type have the CultureSpecificAttribute?

**Comment by wiske80** [comment]
hi frederik... 

yes they do... they are like this:

```
        [CultureSpecific]
        [Display(
            Name = "Filters for news",
            Description = "",
            GroupName = SystemTabNames.Content,
            Order = 2)]
        [UIHint("Tags")]
        public virtual string Filters { get; set; }
```

**Comment by frederikvig** [comment]
Do they work if you remove the CultureSpecificAttribute? I think the problem is with the new feature we added recently (GroupKey and CultureSpecific).

**Comment by wiske80** [comment]
i removed the attribute but still empty..
I tried the call to the api like so: /getatags?term=agenda, then i see the array filled with all my tags starting with 'agenda'.
So what is the groupKey? and why is that preventing my tags to show in the CMS.

**Comment by frederikvig** [comment]
Without the attribute how does the api call look? The groupKey is used for language or specific collections, in order to group tags together in a collection. Default is empty group key.

**Comment by wiske80** [comment]
/getatags?groupKey=&term=agenda

then its like this, but then returns empty array

**Comment by frederikvig** [comment]
I saw there was a bug with empty groupkey (we just checked for null). Updated the package now (version 2.1.3 or later). Should be available soon on the NuGet feed.

**Comment by wiske80** [comment]
thanks... i will try it once available on the feed

**Comment by wiske80** [comment]
how long does it normally take to be available in the nuget feed?

**Comment by frederikvig** [comment]
It was just published now.

**Comment by wiske80** [comment]
Thanks.. so i updated the package... Now the autocomplete works again. So when i type i see the dropdown, but my previously added tags are not visible in the properties... (see screenshots). 

![capture](https://cloud.githubusercontent.com/assets/7689723/11368102/0b3f52ea-92b8-11e5-8752-a8994539c47b.PNG)

I know the properties are filled, because in code if i fetch it, i can see there should be 6 tags in it. See screenshot.
![capture2](https://cloud.githubusercontent.com/assets/7689723/11368187/91406f1e-92b8-11e5-8c1b-33f06a0e7713.PNG)

**Comment by frederikvig** [comment]
No errors in the console? What happens if you remove the UIHint attribute?

**Comment by wiske80** [comment]
strangely no console errors... 
When i remove the UIHint it turns into an textbox and then you see the values stored.  (see screenshot)

![capture](https://cloud.githubusercontent.com/assets/7689723/11374416/4424b488-92d6-11e5-90f4-80279ced8c63.PNG)

I then tried to add the UIHints again hoping to maybe trigger something, but then i just see the empty Tag properties again. 

I tried also with a new page containing tags. I created a new page, i added a tag, published it. See it on the front-end, but when i open the page in CMS again, it shows empty. So it looks like everything is working, selecting, tags, saving tags, but showing the value in the CMS property seems to be an issue...

**Comment by frederikvig** [comment]
Which version of Episerver are you running? Anything particular in that installation (addons, commerce etc).

**Comment by wiske80** [comment]
i'm on a latest 9.3.3

no commerce, just CMS..

addons: Geta Tags, Geta SEO Sitemaps, Geta Epi Extensions, Geta oEmbed, BVN404Handler (latest),
MenuPin, Episerver.GooglemapsEditor.. 

Those are the biggest things. 

The problem is that everything worked fine before upgrading to EPI 9 in combination with updated Geta Tags.

**Comment by xssic** [comment]
I am also having the same behaviour on a site.
Also upgraded to episerver 9.3.3.

Looks to me that it is not loading the tags properly/completely.
The hidden field contains the values.

**Comment by wiske80** [comment]
Good to know i'm not the only one. 

Today i thought to try to reproduce it. I had a old Alloy site which was running on Epi 8.9.0. It didnt had Geta Tags. So i installed my previous geta tags version 2.0.3. 

I created a Tag property and populated it with some tags. 

I then upgraded 8.9.0 to 9.3.3 (updated the database), but didnt update Geta Tags to the latest. I got the error below when starting the site, which is understandable. 
![gata](https://cloud.githubusercontent.com/assets/7689723/11391488/1e7bfbe2-9353-11e5-9674-b2ae135af5c3.PNG)

I then updated Geta.Tags to 2.1.3 and opened the page containing the Tag property. I removed the culturespecific attribute. But also here i see the property is empty.

I hope you guys can reproduce this as well..

**Comment by xssic** [comment]
Look at the dependencies in nuget package manager and you will find that 2.0.3 requires an older version of EPiServer.

**Comment by wiske80** [comment]
i know, i was just describing the reproducing procedure, so that the Geta guys can try it the same way, to come up with a fix. Hopefully quick, because we have a serious problem now.  We have used tagging mechanism quite extensively in the site and it depends heavily on this to work properly.

**Comment by wiske80** [comment]
hi guys any updates? I'm working against a serious deadline for the end of this week. 

So i hope to get this fixed before that... thanks

**Comment by garkavy** [comment]
I will look more on that tomorrow (on Tuesday). What I can suggest now, based on my tests, is to downgrade EPiServer.CMS.Core and Framework to 9.3.2. And EPiServer.CMS.UI and EPiServer.CMS.UI.Core to 9.3.0. Those are the latest versions where Tags are working currently.

**Comment by garkavy** [comment]
It looks like it is EPiServer bug in EPiServer.CMS.UI and EPiServer.CMS.UI.Core. I've noticed related problem with the ordinary textbox control when the relevant input control's "value" is blank. 
Here is the source example:

**Comment by frederikvig** [comment]
@garkavy verify with Episerver support please and link to bug #

**Comment by wiske80** [comment]
thanks for checking @garkavy . I would like the link to Epi bug aswell... so i can see the progress..

**Comment by frederikvig** [comment]
@wiske80 please verify that this is working for you with the latest package (just got published). Thanks to @vansterhant for fixing it

**Comment by wiske80** [comment]
Yess.. this works great in the latest EPiserver... thanks alot @frederikvig and @vansterhant
