### ISSUE TITLE
Does not work in page header

### ISSUE THREAD

**Issue by oskar-ottoboni** [Geta/Tags#31]
Does not show saved tags when the property is placed in the page header. 

[UIHint("Tags")]
[Display(GroupName = SystemTabNames.PageHeader, Order = 50)]
public virtual string Tags { get; set; }

**Comment by marisks** [comment]
@oskar-ottoboni  Could you plase check if it is fixed in latest version (Geta.Tags 2.1.9)?

**Comment by marisks** [comment]
Closing issue because didn't get any response and issue could be fixed in 2.1.9.
