### ISSUE TITLE
Unable to find package 'Geta.Tags'

### ISSUE THREAD

**Issue by Ayoubezzddine** [Geta/Tags#32]
PM> Install-Package Geta.Tags
Install-Package : Unable to find package 'Geta.Tags'
At line:1 char:1
+ Install-Package Geta.Tags
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
PM> 

This is package source:
https://api.nuget.org/v3/index.json

**Comment by frederikvig** [comment]
The package is hosted at nuget.episerver.com

**Comment by Ayoubezzddine** [comment]
I added nuget.episerver.com as package source
But the same error exists

Can you give me more help steps to start

**Comment by frederikvig** [comment]
http://nuget.episerver.com/feed/packages.svc/

**Comment by Ayoubezzddine** [comment]
thank you, fixed

Can you help me with this, how can I call the ITagEngine GetContentByTag(string tagName) in a aspx.cs page

**Comment by frederikvig** [comment]
ServiceLocator.Current.GetInstance&lt;ITagEngine&gt;()

**Comment by Ayoubezzddine** [comment]
Hi frederikvig,

Can we get the topic tags? how to retrieve a list of the highest used tags?

Thank you

**Comment by Ayoubezzddine** [comment]
Any answer..

**Comment by frederikvig** [comment]
There's a count property on the Tag object that you can use for this. Basically you would need to get all tags and then order by count.

**Comment by Ayoubezzddine** [comment]
Thank you but my question is how to get all the tags?

Do I have t get all pages and loop to insert the tags in a list the order them, or is there a function to use?

**Comment by Sebbe** [comment]
TagService have a function called GetAllTags() which should return all tags.

var tagService = ServiceLocator.Current.GetInstance<ITagService>();
var allTags = tagService.GetAllTags();

**Comment by Ayoubezzddine** [comment]
Hi,

Thanks for the great help.

I need to retrieve the related pages based on the tags(multi tags) of my current page.

Should I loop for the tags separated by (,) and get pages related for each instance?

**Comment by Ayoubezzddine** [comment]
Hi,

We have 2 different website in the same solution, I read that we can use (TagsGroupKey("mysite")) for the tags property.

But how can I get the tags for each website alone.

**Comment by Ayoubezzddine** [comment]
any updates??
