### ISSUE TITLE
EPiServer Find and Geta Tags

### ISSUE THREAD

**Issue by wirenpau** [Geta/Tags#33]
I'm using EPiserver Find to find articles that contains any tag or part of tag (free text search).
If an article is tagged "Drive". I want a hit when searching part of the word.
"riv" should get me a search hit.
But I can't make it work. I'm still not sure if this is an issue on the Geta Tag side or on the EPiServer Find side.
EPiServer support told me to put a question in this Forum.

This was I sent to them:

UnifiedSearch - Filtering problem

var hitSpecification = new HitSpecification();

var query = SearchClient.Instance.UnifiedSearch();
query = query.Filter(x => x.MatchTypeHierarchy(typeof(NewsPage)) |     
                               (x.MatchTypeHierarchy(typeof(Blog)) & ((Blog)x).DisplayInNewsFlow.Match(1))

query = query.MatchTags(criterias.Tags);

UnifiedSearchResults searchResult = query.GetResult(hitSpecification);

}

public static ITypeSearch<ISearchContent> MatchTags(
this ITypeSearch<ISearchContent> search, string tags)
{
      var tagsBuilder = SearchClient.Instance.BuildFilter<ISearchContent>();

      // criterias.Tags is a list of strings ie "TT Jec"
      // x.SearchMetaData["Tags"] is also a list of strings ie "TT,AA, Subject,CC"
      foreach (string tag in tags.Split(' ').ToList())
     {
          tagsBuilder =
          tagsBuilder.Or(x => x.SearchMetaData["Tags"].StringValue.Contains(tag).Match(true));
     }

     return search.Filter(tagsBuilder);
}

The goal is to compare those two lists. If one of the strings in criterias.Tags exists or is a part of at 
least one of the strings in x.SearchMetaData["Tags"]. I want that item in the result.

This is working - but I don't want a hit on only AnyWordBeginsWith. I want also a hit when 
AnyWordWith/Contains in the x.SearchMetaData["Tags"] list
tagsBuilder = tagsBuilder.Or(x => x.SearchMetaData["Tags"].StringValue.AnyWordBeginsWith(tag));

   This is not working, Why?
    tagsBuilder = tagsBuilder.Or(x => 
                                     x.SearchMetaData["Tags"].StringValue.Contains(tag).Match(true));
 or

tagsBuilder = tagsBuilder.Or(x => 
                                     x.SearchMetaData["Tags"].StringValue.indexOf(tag).GreaterThan(-1));

   In the exampel above.
   Searching on "Jec" should give a hit on "Subject".

**Comment by frederikvig** [comment]
The tags are just stored as a string comma separated, so Episerver Find should have no problem doing a contains on it. Maybe this will help: http://joelabrahamsson.com/wildcard-queries-with-episerver-find/
