### ISSUE TITLE
tags duplicate and delete

### ISSUE THREAD

**Issue by Ayoubezzddine** [Geta/Tags#39]
I have a website with two roots, i want to use the same tag for the differnet pages under the two roots.

The problem is that if I used the groupkey i will not be able to differeniate which tags for which page.
Also if I want to delete the tag will be deleted from all the pages under the two roots.

Is there a way to use the same tag as duplicate?

**Comment by marisks** [comment]
Do you have same code for both sites? And you reuse same content types (with tags property)?

**Comment by marisks** [comment]
Closing as no answer for several months. If it is still actual, please re-open the issue.
