### ISSUE TITLE
Gheta.Tags breaks EPiServer.ContentCollaboration in chrome

### ISSUE THREAD

**Issue by jgreene** [Geta/Tags#40]
The error is
epi.js:2 TypeError: $.hubConnection is not a function

This is due to Gheta.Tags including its own version of jQuery and overwriting the version that already exists.  Removing the reference to jquery breaks the included jquery.ui version.

I would recommend using jquery noconflict, but I'm not sure that is possible given the plugins required for this plugin.

**Comment by marisks** [comment]
Just installed EPiServer.ContentCollaboration (1.2.0.9000) and latest Geta.Tags (2.1.17) version and do not have any issues. Everything works. I have EPiServer.CMS 9.12.0.

**Comment by marisks** [comment]
After cleaning the cache, have this issue too. Will check what can be done.

**Comment by marisks** [comment]
Here is related issue on EPiServer forum: http://world.episerver.com/forum/developer-forum/Addons/Thread-Container/2016/2/content-collaboration-signalr-problem/?pageIndex=1#reply

**Comment by marisks** [comment]
THACH Lockevn posted solution on: http://world.episerver.com/forum/developer-forum/Addons/Thread-Container/2016/2/content-collaboration-signalr-problem/?pageIndex=1#reply
