### ISSUE TITLE
Version is not writable

### ISSUE THREAD

**Issue by jeroenslor** [Geta/Tags#41]
I have added the tags property to my content type using the following code:
`[UIHint("Tags")]
        [Display(
            Name = "Tags",
            Description = "The tags",
            GroupName = GroupNames.Tabs.MetaData,
            Order = 11)]
        [CultureSpecific]
        public virtual string Tags { get; set; }`

When I add a tag to the tags field using the CMS interface I get the following generic error during auto save (and also during publish):
![image](https://cloud.githubusercontent.com/assets/3592413/17170759/d5dca376-53ed-11e6-9144-a2d75734d4d0.png)

See attachment for the stack trace of the underlying error that occurs on /EPiServer/cms/Stores/contentdata/114_525:
[geta_tags_error_stack.txt](https://github.com/Geta/Tags/files/385735/geta_tags_error_stack.txt)

I'm using CSM version 9.12.0

**Comment by marisks** [comment]
Just tested on empty EPiServer site - upgraded to CMS 9.12.0 (latest version now) and there are no issues.
This looks like the issue: http://world.episerver.com/forum/developer-forum/EPiServer-7-CMS/Thread-Container/2012/12/offline-cant-save---error/

Also, do you have latest EPiServer.CMS.UI package (9.8.3)?

**Comment by marisks** [comment]
Closing issue because didn't get any response. Feel free to re-open if it is still actual.

**Comment by jeroenslor** [comment]
@marisks You where right it had nothing todo with Geta Tags, thanks for the response!
