### ISSUE TITLE
Tag Data Store not mirrored in EPiServer 9.2

### ISSUE THREAD

**Issue by trevorrebelo** [Geta/Tags#43]
Hi, 

Thanks for developing this feature, we have implemented Geta Tags in our EPiServer 9.2 instance and its working good, except for when we do mirroring. 
The datastore is not getting mirrored.  The string property values are getting mirrored but not the Tag data store. 

Please let me know if i have missed anything.

**Comment by marisks** [comment]
Tags are saved in DDS. Make sure that DDS's tblBigTable is mirrored.

**Comment by trevorrebelo** [comment]
Hello Marisks, 

I thought the code in TagsTransferModule.cs was to enable mirroring of the Tag DDS. Can you pls advise how to mirror the tblBIgTable ? Any pointers would be hlepful.

**Comment by marisks** [comment]
You are right - seems that TagsTransferModule.cs should do that. Didn't know about it. Have you tried to debug it - attach to the code in the TagsTransferModule?
