### ISSUE TITLE
Create Tag property with a key

### ISSUE THREAD

**Issue by akkivinaya** [Geta/Tags#45]
Hi All,
I want to create a tag property with a key like below example
[TagsGroupKey("mykey")]
[UIHint("Tags")]
public virtual string Tags { get; set; }
but TagsGroupKey is not idetifiable.Can anybody help me how to get it.

**Comment by marisks** [comment]
TagsGroupKey is available here: https://github.com/Geta/Tags/blob/master/src/Attributes/TagsGroupKeyAttribute.cs

So add using for this namespace: Geta.Tags.Attributes
