### ISSUE TITLE
Geta Tags Admin Interface gives 404

### ISSUE THREAD

**Issue by wiske80** [Geta/Tags#47]
Hi Guys,

i just updated the Geta.Tags package to the latest version 2.1.17 just for the nice new admin interface to remove/edit tags.

Update goes well, but when i go to admin --> tools --> Geta tags management i get a 404 error.
The urls points to /GetaTagsAdmin/Index 

So what am i missing here? Looks like it can't find the Index view.

I see in my solution under Modules -> Geta.Tags -->2.1.17 --> Views --> Admin --> Index.cshtml
So the files are there... 

can someone pls give some insight? 
I also update EPi to the current latest version.

**Comment by wiske80** [comment]
I had another project aswell... and updated the Geta Tags there as well, just to see if it would work there... and i get the 404 there as well on the Admin interface page.  
So i could reproduce it on 2 different projects.

**Comment by EricHerlitz** [comment]
The GetaTagsAdminController.cs points to the URL /GetaTagsAdmin/Index, which is causing the error. The correct url is /GetaTagsAdmin. Hence navigate to your site and add GetaTagsAdmin, i.e. http://www.yoursite.com/GetaTagsAdmin 

This should be fixed however

**Comment by wiske80** [comment]
thanks Eric ... but stilll the Edit and Delete buttons on the admin screen give 404 as well..

**Comment by patkleef** [comment]
Solved in latest version 2.2.1

**Comment by wiske80** [comment]
Hi,

so you fixed the admin overview page of all the tags, but the edit and delete buttons still give 404 error when clicking. 

Can we expect an update soon?
