### ISSUE TITLE
Tags aren't Episerver 10 compatible

### ISSUE THREAD

**Issue by kennygutierrez** [Geta/Tags#49]
After adding Tags to SitePageData the All Properties view becomes inaccessible.

**Comment by frederikvig** [comment]
Hi Kenny, which version are you using (both Episerver and Tags) and what does the error message in your browser`s console say?

**Comment by kennygutierrez** [comment]
Latest Episerver 10.0.2 and latest tags 2.1.17. Can be reproduced by creating a new Alloy site and added Tags to SitePageData. 

I get three errors:

1. 404 on /EPiServer/Shell/10.0.2.0/ClientResources/geta-tags.TagsSelection.js
2. Some script error on lin 15 of dojo.js
3. Some error with line 2 of widgets.js

![2016-11-11_1426](https://cloud.githubusercontent.com/assets/5246906/20229227/d9e76d44-a81a-11e6-98da-929af97d7f87.png)

**Comment by frederikvig** [comment]
We haven`t upgraded Geta.Tags to support Episerver 10 yet. It`s however on our TODO-list.

**Comment by kennygutierrez** [comment]
Ok, thanks!

**Comment by frederikvig** [comment]
For reference, once I figure out my question here: http://world.episerver.com/forum/developer-forum/-Episerver-75-CMS/Thread-Container/2016/11/transfermodule-dds-and-episerver-10/ we should be able to finish the upgrade.

**Comment by patkleef** [comment]
Hi @kennygutierrez ,

Upgrade to the latest version: http://nuget.episerver.com/en/OtherPages/Package/?packageId=Geta.Tags&packageVersion=2.2.1

Should solve your problem.

**Comment by kennygutierrez** [comment]
Looks like that did it! Thanks for the prompt response!!
