### ISSUE TITLE
Tags CustomProperty not in Admin View after Install.

### ISSUE THREAD

**Issue by apbritt98** [Geta/Tags#53]
After installing Geta.Tags with Nuget, there is no CustomProperty for tags in the Admin View. I also cannot edit any page or block with a Tag Property.

**Comment by marisks** [comment]
Could you provide a code snippet how you defined properties for tags?

**Comment by apbritt98** [comment]
Resolved: This was an issue with EPiServer admin privileges, not Geta.Tags
