### ISSUE TITLE
Feature Request - Sortable tags

### ISSUE THREAD

**Issue by robgha01** [Geta/Tags#59]
Hi

First and all i would like to thank you for this great plugin.
Im wondering if it is possible to make the tags sortable with the use of ex drag & drop, i researched a bit on the net and found this two posts:
https://stackoverflow.com/questions/5222206/how-can-i-make-this-tagging-system-sortable
https://stackoverflow.com/questions/14553917/using-sortable-with-tag-it-jqueryui

From what i can see at the tag-it doc's no sortable feature exists out of the box.

**Comment by neanerea2018** [comment]
Would be a very nifty feature for sure.

**Comment by marisks** [comment]
This solution should work: https://github.com/aehlke/tag-it/issues/224#issuecomment-30280976

**Comment by marisks** [comment]
Fixed in 3.0.3
