### ISSUE TITLE
GroupKey is based on CMS language regardless of site language

### ISSUE THREAD

**Issue by marklarsa** [Geta/Tags#65]
The CultureSpecificAttribute sets the GroupKey value depending on CMS language, meaning an editor would have to change his personal language to create language-specific tags on a multi-language setup. Perhaps setting the groupkey value depending on the ContantLanguage would be better. That way an editor with his/her CMS-language set to English could create tags on separate language sites.

The problem occurs when for example a user has selected English as 'CMS language', and a page was created for the Norwegian language, then the entered tags are marked as English.

**Comment by patkleef** [comment]
New package published to the EPiServer feed: 3.0.4.
