### ISSUE TITLE
Removing a tag from a page doesn't remove the page from the list where it's displayed

### ISSUE THREAD

**Issue by mariajemaria** [Geta/Tags#70]
Using GetContentReferencesByTags on an article list page to show any articles with the same tag.

Steps to reproduce:

1. Find/create Article list page and Article Page(s) that have common tags
2. Remove the common tag from Article Page(s) and publish
3. Check resulting Article page list.
4. The page is still there.

(On the other hand, adding a new tag, instantly works - shows the page).

Running Maintenance scheduled job doesn't help.

The site is available only in Norwegian.

**Comment by wiske80** [comment]
I experience the exact same problem as @mariajemaria with the GetContentReferencesByTags methods.

_Along with the above problem there is another one:_

Another problem with GetContentReferencesByTags, when i give as a parameter a comma seperated string of tagNames e.g ("news_kc,news_fd,news_ko_test"), the method also return contentreferences which do not have any of the tags given in the comma seperated list. 

I am 100% sure that this was working fine before. This has been running for 2 years now in a production environment and today the client saw these weird behaviors.

I Am running on the latest GetaTags 2.0.4 . I can see some things changed with this method, but nothing that would break it. I also tried to convert each tag from string to the Tag Model en then feed it to the GetContentReferencesByTags method, but even then it returns references which do not have the tag.

The Maintenance scheduled job has also ran multiple time, but also doesn't help.

So either the method broke or the scheduled job is.

**Comment by wiske80** [comment]
After some more research i can confirm that when downgrading back to 4.0.0 the above problem doesn't exist. 
So i guess it was introduced in version 4.0.1 and above.

For now i'm downgrading back to 4.0.0.

**Comment by marisks** [comment]
Is this issue still in 4.0.2? I have fixed one issue regarding languages recently in 4.0.2. It might be related.

**Comment by mariajemaria** [comment]
We have 4.0.1, but I can do an upgrade and give it a check if it's fixed in 4.0.2.

**Comment by wiske80** [comment]
I did an upgrade as i mentioned before but no juice, but maybe @mariajemaria can confirm on her side as well..

**Comment by mariajemaria** [comment]
We finally found time on project to check, no luck with 4.0.2 either.

**Comment by marisks** [comment]
Is it for old tags you already had or new tags too?

P.S. There might be issues with old tags in 4.0.2.

**Comment by wiske80** [comment]
> 
> 
> Is it for old tags you already had or new tags too?
> 

In my case the problem were with existing tags in the system.

**Comment by mariajemaria** [comment]
We tested with new tags only.

**Comment by mariajemaria** [comment]
Added the pull request: https://github.com/Geta/Tags/pull/74
