### ISSUE TITLE
InvalidCastException when trying to edit tags for Block

### ISSUE THREAD

**Issue by jdbrn** [Geta/Tags#95]
The option to edit existing tags in Tags Management throws an error when used on a Block or any other type of content that's not PageData. 

![image](https://user-images.githubusercontent.com/18525440/66742738-a26c3f00-ee78-11e9-8601-83024a498375.png)

Caused by this explicit cast to PageData:
`PageData writableClone = ((PageData) this._contentRepository.Get<IContent>(contentReferencesByTag)).CreateWritableClone();`

**Comment by patkleef** [comment]
@jdbrn fixed in version 4.0.12. It will be available on the Episerver NuGet feed when the package is approved.
